version: "3.7"

services:

  # app:
  #   build:
  #     dockerfile: ./Dockerfile
  #     context: ./
  #   command: npm run start
  #   restart: on-failure
  #   volumes:
  #     - ${PWD}/data/cln:/cln/.lightning
  #     - ${PWD}/data/app:/data
  #   environment:
  #     PORT: "3007"
  #     BITCOIN_HOST: "bitcoind"
  #     RPC_PORT: "18443"
  #     RPC_USER: "usr"
  #     RPC_PASSWORD: "usr"
  #     CLN_NETWORK: "regtest"
  #     CLN_HOST: "cln"
  #     CHANNEL_BACKUP_FILE: /data/.lightning/channel.backup
  #     BACKUP_STATUS_FILE: /data/.lightning/backup-status.json
  #     JSON_STORE_FILE: /data/app/state.json
  #     EXPLORER_PORT: 1235
  #     EXPLORER_HIDDEN_SERVICE: 'mempool.onion'
  #     TOR_PROXY_IP: tor
  #     TOR_PROXY_PORT: 9051
  #     DEVICE_HOSTNAME: test.local
  #   ports:
  #     - "3007:3007"

  cln:
    image: lncm/clightning:latest@sha256:7f3a3719ab6948451e92613ecb92aba5f8a2d145a7de0eb58992855fc1d7eb65
    user: 1000:1000
    hostname: cln
    command: --network=regtest --lightning-dir=/data/.lightning
    volumes:
      - ${PWD}/data/cln:/data/.lightning
    environment:
      HOME: /data

  bitcoind:
    image: lncm/bitcoind:v24.0@sha256:db19fe46f30acd3854f4f0d239278137d828ce3728f925c8d92faaab1ba8556a
    user: 1000:1000
    command: -regtest -datadir=/data/.bitcoin
    volumes:
      - ${PWD}/data/bitcoin:/data/.bitcoin
