version: "3.7"

services:
  bitcoind:
    image: lncm/bitcoind:v24.0@sha256:db19fe46f30acd3854f4f0d239278137d828ce3728f925c8d92faaab1ba8556a
    command:
      - -${APP_CORE_LIGHTNING_BITCOIN_NETWORK}
      - -rpcbind=0.0.0.0
      - -rpcallowip=0.0.0.0/0
      - -rpcauth=umbrel:5071d8b3ba93e53e414446ff9f1b7d7b$$375e9731abd2cd2c2c44d2327ec19f4f2644256fdeaf4fc5229bf98b778aafec
    restart: on-failure
    volumes:
      - ${PWD}/data/bitcoin:/data/.bitcoin

  cln:
    image: elementsproject/lightningd:v22.11.1@sha256:14f1a7937f9692184e46ab6245ed51ed86262d208e81fd5ec5f0339ac5bf8096
    depends_on:
      - bitcoind
    ports:
      - ${APP_CORE_LIGHTNING_DAEMON_PORT}:9735
    command: 
      - --bitcoin-rpcconnect=${APP_BITCOIN_NODE_IP}
      - --bitcoin-rpcuser=${APP_BITCOIN_RPC_USER}
      - --bitcoin-rpcpassword=${APP_BITCOIN_RPC_PASS}
      - --bind-addr=${APP_CORE_LIGHTNING_DAEMON_IP}:9735
      - --network=${APP_CORE_LIGHTNING_BITCOIN_NETWORK}
      - --experimental-websocket-port=5001
      - --experimental-offers
#      - --proxy=${TOR_PROXY_IP}:${TOR_PROXY_PORT}
#      - --addr=statictor:${TOR_PROXY_IP}:29051
#      - --tor-service-password=${TOR_PASSWORD}
    restart: on-failure
    volumes:
      - ${PWD}/data/lightning:/data/.lightning
    networks:
      default:
        ipv4_address: ${APP_CORE_LIGHTNING_DAEMON_IP}

  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    depends_on:
      - bitcoind
      - cln
    command: npm run start
    restart: on-failure
    volumes:
      - ${PWD}/data/lightning:/data/.lightning
      - ${PWD}/data/app:/data/app
    environment:
      APP_HOST: "${APP_CORE_LIGHTNING_IP}"
      APP_PORT: "${APP_CORE_LIGHTNING_PORT}"
      APP_CORE_LIGHTNING_DAEMON_IP: "${APP_CORE_LIGHTNING_DAEMON_IP}"
      APP_CORE_LIGHTNING_RUNE: "${APP_CORE_LIGHTNING_RUNE}"
      APP_CORE_LIGHTNING_WS_PORT: ${APP_CORE_LIGHTNING_WS_PORT}
      APP_CORE_LIGHTNING_NODE_PUBKEY: "${APP_CORE_LIGHTNING_NODE_PUBKEY}"
      APP_CORE_LIGHTNING_APPLICATION_MODE: "${APP_CORE_LIGHTNING_APPLICATION_MODE}"
      APP_CORE_LIGHTNING_CONFIG_LOCATION: "${APP_CORE_LIGHTNING_CONFIG_LOCATION}"
      APP_CORE_LIGHTNING_LOG_FILE_LOCATION: "${APP_CORE_LIGHTNING_LOG_FILE_LOCATION}"
      APP_CORE_LIGHTNING_TOR_HOST: "${APP_CORE_LIGHTNING_TOR_HOST}"
    ports:
      - "${APP_CORE_LIGHTNING_PORT}:${APP_CORE_LIGHTNING_PORT}"
    networks:
      default:
        ipv4_address: ${APP_CORE_LIGHTNING_IP}
