version: "3.8"

services:
  bitcoind:
    image: lncm/bitcoind:v24.0@sha256:db19fe46f30acd3854f4f0d239278137d828ce3728f925c8d92faaab1ba8556a
    command:
      - -${APP_CORE_LIGHTNING_BITCOIN_NETWORK}
      - -rpcbind=0.0.0.0
      - -rpcallowip=0.0.0.0/0
      - -rpcauth=umbrel:5071d8b3ba93e53e414446ff9f1b7d7b$$375e9731abd2cd2c2c44d2327ec19f4f2644256fdeaf4fc5229bf98b778aafec
    restart: on-failure
    volumes:
      - ${PWD}/data/bitcoin:/data/.bitcoin

  lightning:
    image: elementsproject/lightningd:v22.11.1@sha256:14f1a7937f9692184e46ab6245ed51ed86262d208e81fd5ec5f0339ac5bf8096
    command: 
      - --bitcoin-rpcconnect=bitcoind
      - --bitcoin-rpcuser=umbrel
      - --bitcoin-rpcpassword=moneyprintergobrrr
      - --network=regtest
      - --log-level=debug
      - --experimental-websocket-port=${APP_CORE_LIGHTNING_WS_PORT}
      - --experimental-offers
    restart: on-failure
    volumes:
      - ${PWD}/data/bitcoin:/data/.bitcoin
      - ${PWD}/data/lightning:/data/.lightning
    networks:
      default:
        ipv4_address: ${APP_CORE_LIGHTNING_DAEMON_IP}

  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    depends_on:
      - bitcoind
      - lightning
    command: npm run start
    restart: on-failure
    volumes:
      - ${PWD}/data/app:/data/app
    environment:
      APP_HOST: "${APP_CORE_LIGHTNING_IP}"
      APP_PORT: "${APP_CORE_LIGHTNING_PORT}"
      APP_DATA_DIR: "${APP_DATA_DIR}"
      APP_CORE_LIGHTNING_DAEMON_IP: "${APP_CORE_LIGHTNING_DAEMON_IP}"
      APP_CORE_LIGHTNING_RUNE: "${APP_CORE_LIGHTNING_RUNE}"
      APP_CORE_LIGHTNING_NODE_PUBKEY: "${APP_CORE_LIGHTNING_NODE_PUBKEY}"
      APP_CORE_LIGHTNING_WS_PORT: ${APP_CORE_LIGHTNING_WS_PORT}
      APP_CORE_LIGHTNING_TOR_HOST: "${APP_CORE_LIGHTNING_TOR_HOST}"
      LIGHTNING_GRPC_PORT: "${LIGHTNING_GRPC_PORT}"
      LIGHTNING_REST_PORT: "${LIGHTNING_REST_PORT}"
      LIGHTNING_REST_MACAROON_PATH: "${LIGHTNING_REST_MACAROON_PATH}"
      LIGHTNING_REST_HIDDEN_SERVICE: "${LIGHTNING_REST_HIDDEN_SERVICE}"
      LOCAL_HOST: "${LOCAL_HOST}"
      CA_CERT: "${CA_CERT}"
      CLIENT_KEY: "${CLIENT_KEY}"
      CLIENT_CERT: "${CLIENT_CERT}"
    ports:
      - "${APP_CORE_LIGHTNING_PORT}:${APP_CORE_LIGHTNING_PORT}"
    networks:
      default:
        ipv4_address: ${APP_CORE_LIGHTNING_IP}
