name: Build and publish Docker image

on:
  push:
    branches: [ 'release-*' ]
    tags: [ 'v*' ]
  release:
    types: [released]
  pull_request:
    types: [closed]
    branches: [ master ]
  workflow_dispatch:
  
env:
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:
  build:
    name: Build image
    runs-on: ubuntu-22.04

    steps:
      - name: Set env variables
        run: |
          echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@@v2
        id: qemu

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@@v2
        id: buildx

      - name: Run Docker buildx
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64,linux/arm/v7 \
          --tag ${{ secrets.DOCKER_HUB_USER }}/umbrel-core-lightning:$BRANCH \
          --push .
